### PR TITLE
Import from intel-igc-5.10.214-3.xs8.src.rpm

### PR DESCRIPTION
**Pull request by tescande**
This imports sources and patches from intel-igc-5.10.214-3.xs8.src.rpm, rebases 0004-showversion.patch, and drops 0005-i226.patch per Andrew feedback.

### CODE REVIEW

**Comment by tescande** [comment]
Hi @andrew64k,
Pinging you as I cannot add you as reviewer.
Regards

**Comment by stormi** [comment]
So, given that we decided to go with XenServer's version of the patches (with the possible addition of the showversion patch and the i226 patch), I think we should import theirs directly and make it obsolete `igc-module`. This will likely make future maintenance easier.

**Comment by stormi** [comment]
I imported the `intel-igc` SRPM to https://github.com/xcp-ng-rpms/intel-igc. You can create a PR there to 1. Obsolete igc-module <= current version-release, 2. add the showversion and i226 patches.

**Review by gduperrey — APPROVED** [review]

**Comment by tescande** [comment]
This repository has been moved to a new one named [xcp-ng-rpms/intel-igc](https://github.com/xcp-ng-rpms/intel-igc/).

This PR is also merged in the new repo by this [PR](https://github.com/xcp-ng-rpms/intel-igc/pull/1).

**Pull request closed without merging**
