### PR TITLE
Update from upstream kernel source 5.10.226

### PR DESCRIPTION
**Pull request by andrew64k**
Change to use Xen/XCP 8.3 IGC code that is the same with minor patch cleanup
Minor lock fix on error return (upstream kernel code update)

### CODE REVIEW

**Comment by stormi** [comment]
Hi! Can you describe when the error can be triggered and what the consequences for this error are?

**Comment by andrew64k** [comment]
It's not a common error. After an IO error and reset if the card can't be opened again a lock is left in place at the return from the function. The fix adds the unlock. I would guess this error would cause the IGC driver to be unusable after the error (without the fix).

I don't think you can force the error/bug to happen in testing. It's also not something that should happen in normal use. This is not code that changes normal operation, just an error handling routine.

Here's the upstream kernel [commit ef4a99a0164e3972abb421cbb1b09ea6c61414df](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/drivers/net/ethernet/intel/igc/igc_main.c?id=ef4a99a0164e3972abb421cbb1b09ea6c61414df)

**Comment by stormi** [comment]
Switching to 8.3's intel-igc is planned for 8.2, but this will happen on the intel-igc repository, not this one, because the package name will change. So this PR should limit itself to patching the issue described above.

**Comment by andrew64k** [comment]
Ok.

**Comment by stormi** [comment]
@tescande Have you already ported this fix to the other repo for 8.2? I think I remember something about it.

**Comment by tescande** [comment]
> @tescande Have you already ported this fix to the other repo for 8.2? I think I remember something about it.

@andrew64k has already opened a [PR](https://github.com/xcp-ng-rpms/intel-igc/pull/2) for this 5.10.226 to the 8.3 repo and we will use it for 8.2 as well once the requested changes are done and merged.

**Comment by stormi** [comment]
Thanks. So let's close this one and focus on https://github.com/xcp-ng-rpms/intel-igc/pull/2

**Pull request closed without merging**
